export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_CENTER_SUCCESS = "LOAD_CENTER_SUCCESS";
export const UPDATE_CENTER = "UPDATE_CENTER";

export const LOAD_SELECT_CENTERS_SUCCESS = "LOAD_SELECT_CENTERS_SUCCESS";

export const LOAD_CENTER_FUND_SUCCESS = "LOAD_CENTER_FUND_SUCCESS";
